"""empty message

Revision ID: 517414d277fa
Revises: 3dd7f3305df9
Create Date: 2024-03-14 11:40:42.628959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '517414d277fa'
down_revision = '3dd7f3305df9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
